### ISSUE TITLE
List tasks we discussed for early next week

### ISSUE THREAD

**Issue by nniiicc** [BITS-Research/Annotations#1]

**Comment by ghost** [comment]
Ana:
- Summarize notes from Hunter article and identify areas of investigation
- Outline sections of updated chapter
- Schedule meeting to review protocol

Nic:
- Share systematic analysis protocol with Ana

**Comment by ghost** [comment]
I saw the protocol in the Wiki and will read through those early next week, let me know if there is something else additionally.

**Comment by nniiicc** [comment]
This is a good overview of conducting a systematic review https://lib.guides.umd.edu/SR/steps - What we'll work on for next week are steps 1-4.
